# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-30 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Encoder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractedMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extractedMessage', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='encoding',
            old_name='compressedString',
            new_name='compressedMessage',
        ),
        migrations.AddField(
            model_name='encoding',
            name='compressionEfficiency',
            field=models.FloatField(null=True),
        ),
    ]
