# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-31 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Encoder', '0002_auto_20161230_2259'),
    ]

    operations = [
        migrations.RenameField(
            model_name='encoding',
            old_name='key',
            new_name='key_1',
        ),
        migrations.AddField(
            model_name='encoding',
            name='key_2',
            field=models.TextField(null=True),
        ),
    ]
